// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMDzG1Y0ROPMUr6q5JdLxC1SNYoUHNUhM',
    appId: '1:701098281444:web:b7b0277439b9d1ee0e5ff1',
    messagingSenderId: '701098281444',
    projectId: 'productsapp-27b6d',
    authDomain: 'productsapp-27b6d.firebaseapp.com',
    storageBucket: 'productsapp-27b6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD08T1aWCVYdlyIgxc9Q7EisTki5gRYwj0',
    appId: '1:701098281444:android:d8403a24bf93ea7a0e5ff1',
    messagingSenderId: '701098281444',
    projectId: 'productsapp-27b6d',
    storageBucket: 'productsapp-27b6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6EI_eYpUoEKcYAE3z8XiuSDtDZnxBBy8',
    appId: '1:701098281444:ios:f8bcbc4aff1d7f930e5ff1',
    messagingSenderId: '701098281444',
    projectId: 'productsapp-27b6d',
    storageBucket: 'productsapp-27b6d.appspot.com',
    iosClientId: '701098281444-nhn6rpi32nd35u4v2dqec0lipvu2boha.apps.googleusercontent.com',
    iosBundleId: 'com.example.productosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6EI_eYpUoEKcYAE3z8XiuSDtDZnxBBy8',
    appId: '1:701098281444:ios:f8bcbc4aff1d7f930e5ff1',
    messagingSenderId: '701098281444',
    projectId: 'productsapp-27b6d',
    storageBucket: 'productsapp-27b6d.appspot.com',
    iosClientId: '701098281444-nhn6rpi32nd35u4v2dqec0lipvu2boha.apps.googleusercontent.com',
    iosBundleId: 'com.example.productosApp',
  );
}
